######################################################################
# Automatically generated by qmake (2.01a) ? 11? 10 00:21:50 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += interface.cpp
