######################################################################
# Automatically generated by qmake (2.01a) ? 11? 10 09:35:50 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += interface.h
SOURCES += interface.cpp main.cpp
