######################################################################
# Automatically generated by qmake (2.01a) ? 11? 10 00:19:59 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += Interface.cpp
